# badge: https://github.com/bepasty/bepasty-server/workflows/CI/badge.svg?branch=master

name: CI

on:
  push:
    branches: [ master ]
    paths:
    - '**.py'
    - '**.yml'
    - '**.cfg'
    - '**.ini'
    - 'requirements.d/*'
    - '!docs/**'
  pull_request:
    branches: [ master ]
    paths:
    - '**.py'
    - '**.yml'
    - '**.cfg'
    - '**.ini'
    - 'requirements.d/*'
    - '!docs/**'

jobs:
  lint:

    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 src scripts setup.py

  pytest:

    needs: lint

    strategy:
      matrix:
        include:
            - os: ubuntu-20.04
              python-version: '3.7'
              toxenv: py37
            - os: ubuntu-20.04
              python-version: '3.8'
              toxenv: py38
            - os: ubuntu-20.04
              python-version: '3.9'
              toxenv: py39
            - os: ubuntu-20.04
              python-version: '3.10'
              toxenv: py310
            - os: ubuntu-20.04
              python-version: '3.11'
              toxenv: py311

    env:
      TOXENV: ${{ matrix.toxenv }}

    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3
      with:
        # just fetching 1 commit is not enough for setuptools-scm, so we fetch all
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python requirements
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.d/dev.txt
    - name: run pytest via tox
      run: |
        tox --skip-missing-interpreters
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      env:
        OS: ${{ runner.os }}
        python: ${{ matrix.python-version }}
      with:
        env_vars: OS, python
